### PR TITLE
Try to remove --openssldir on non-windows

### PR DESCRIPTION
**Pull request by ulrikstrid**
Trying to see if this works better in docker

### CODE REVIEW

**Comment by wokalski** [comment]
I don't get what's the goal of this change (?)

**Comment by ulrikstrid** [comment]
It seems like macOS and Linux finds the certs correctly without the flag so it's just needed for Windows.
The flag also breaks static binaries since they will be looking for the CA certs in the esy path instead of the standard path

**Comment by wokalski** [comment]
I see, that's good to know. Sorry for not spotting it earlier. Have you tested it?

**Comment by ulrikstrid** [comment]
It seems to work locally but I want to nail down the docker story before merging this

**Comment by ulrikstrid** [comment]
It seems like this is not needed, we can override where it looks up the certs via environment variables instead.

Where can we document how to do that?
In the docker repo maybe?

**Comment by wokalski** [comment]
We'll figure out where. But just one question. We don't want to specify openssldir (i.e. where to find the certs) because? (I missed that)

**Comment by ulrikstrid** [comment]
I think we do since it "just works" when running with esy. But when you're building a static binary and move it to a container without the esy install dir it will still look in that dir unless you set some environment variables.

Closing this and adding a task to the board instead.

**Pull request closed without merging**
